config/routes.rb
Rails.application.routes.draw do
  
  resources :sequences
  

  resources :mercantiles do
    resources :appearers
  end


  devise_for :users
  
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appearer.rb
class Appearer < ApplicationRecord
  belongs_to :user
  belongs_to :mercantile

  validates_presence_of :user_id, :mercantile_id, :apellidos, :nombres, :identificacion
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mercantile.rb
class Mercantile < ApplicationRecord
  belongs_to :user
  has_many :appearer, dependent: :destroy

  validates_presence_of :user_id, :acto, :observacion, :secuencia, :fecha
  
end

app/models/sequence.rb
class Sequence < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id, :secuencia, :fecha
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sequence
  has_many :mercantile
  has_many :appearer
end

app/controllers/appearers_controller.rb
class AppearersController < ApplicationController
  before_action :set_appearer, only: [:show, :edit, :update, :destroy]
  before_action :set_mercantile
  before_action :authenticate_user!, except: [:index, :show]

  # GET /appearers
  # GET /appearers.json
  def index
    @appearers = Appearer.all
  end

  # GET /appearers/1
  # GET /appearers/1.json
  def show
  end

  # GET /appearers/new
  def new
    @appearer = Appearer.new
  end

  # GET /appearers/1/edit
  def edit
  end

  # POST /appearers
  # POST /appearers.json
  def create
    @appearer = current_user.appearer.new(appearer_params)
    @appearer.mercantile = @mercantile

    respond_to do |format|
      if @appearer.save
        format.html { redirect_to @appearer.mercantile, notice: 'Appearer was successfully created.' }
        format.json { render :show, status: :created, location: @appearer.mercantile }
      else
        format.html { render :new }
        format.json { render json: @appearer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appearers/1
  # PATCH/PUT /appearers/1.json
  def update
    respond_to do |format|
      if @appearer.update(appearer_params)
        format.html { redirect_to @appearer.mercantile, notice: 'Appearer was successfully updated.' }
        format.json { render :show, status: :ok, location: @appearer.mercantile }
      else
        format.html { render :edit }
        format.json { render json: @appearer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appearers/1
  # DELETE /appearers/1.json
  def destroy
    @appearer.destroy
    respond_to do |format|
      format.html { redirect_to mercantile_path(@mercantile), notice: 'Appearer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appearer
      @appearer = Appearer.find(params[:id])
    end
    def set_mercantile
      @mercantile = Mercantile.find(params[:mercantile_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appearer_params
      params.require(:appearer).permit(:user_id, :mercantile_id, :apellidos, :nombres, :identificacion)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mercantiles_controller.rb
class MercantilesController < ApplicationController
  before_action :set_mercantile, only: [:show, :edit, :update, :destroy]
  before_action :set_sequence
  before_action :authenticate_user!, except: [:index, :show]

  # GET /mercantiles
  # GET /mercantiles.json
  def index
    @mercantiles = Mercantile.all
  end

  # GET /mercantiles/1
  # GET /mercantiles/1.json
  def show
  end

  # GET /mercantiles/new
  def new
    @mercantile = Mercantile.new
  end

  # GET /mercantiles/1/edit
  def edit
  end

  # POST /mercantiles
  # POST /mercantiles.json
  def create
    @mercantile = current_user.mercantile.new(mercantile_params)
    @mercantile.secuencia = @sequence.secuencia
    @mercantile.fecha = @sequence.fecha

    respond_to do |format|
      if @mercantile.save
        @sequence.update(secuencia: @mercantile.secuencia+1)
        format.html { redirect_to @mercantile, notice: 'Mercantile was successfully created.' }
        format.json { render :show, status: :created, location: @mercantile }
      else
        format.html { render :new }
        format.json { render json: @mercantile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mercantiles/1
  # PATCH/PUT /mercantiles/1.json
  def update
    respond_to do |format|
      if @mercantile.update(mercantile_params)
        format.html { redirect_to @mercantile, notice: 'Mercantile was successfully updated.' }
        format.json { render :show, status: :ok, location: @mercantile }
      else
        format.html { render :edit }
        format.json { render json: @mercantile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mercantiles/1
  # DELETE /mercantiles/1.json
  def destroy
    @mercantile.destroy
    respond_to do |format|
      format.html { redirect_to mercantiles_url, notice: 'Mercantile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mercantile
      @mercantile = Mercantile.find(params[:id])
    end

    def set_sequence
      @sequence = Sequence.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mercantile_params
      params.require(:mercantile).permit(:user_id, :acto, :observacion, :secuencia, :fecha)
    end
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :set_sequence, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /sequences
  # GET /sequences.json
  def index
    @sequences = Sequence.all
  end

  # GET /sequences/1
  # GET /sequences/1.json
  def show
  end

  # GET /sequences/new
  def new
    @sequence = Sequence.new
  end

  # GET /sequences/1/edit
  def edit
  end

  # POST /sequences
  # POST /sequences.json
  def create
    @sequence = current_user.sequence.new(sequence_params)

    respond_to do |format|
      if @sequence.save
        format.html { redirect_to @sequence, notice: 'Sequence was successfully created.' }
        format.json { render :show, status: :created, location: @sequence }
      else
        format.html { render :new }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sequences/1
  # PATCH/PUT /sequences/1.json
  def update
    respond_to do |format|
      if @sequence.update(sequence_params)
        format.html { redirect_to @sequence, notice: 'Sequence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sequence }
      else
        format.html { render :edit }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sequences/1
  # DELETE /sequences/1.json
  def destroy
    @sequence.destroy
    respond_to do |format|
      format.html { redirect_to sequences_url, notice: 'Sequence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence
      @sequence = Sequence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sequence_params
      params.require(:sequence).permit(:user_id, :secuencia, :fecha)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end

  def unregistered
  end

end

app/helpers/appearers_helper.rb
module AppearersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mercantiles_helper.rb
module MercantilesHelper
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/appearers/_form.html.haml
= simple_form_for [@mercantile, @appearer], html: { class: 'form-horizontal' } do |f|
  = f.error_notification
  
  .form-group
    =f.label :apellidos, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :apellidos, class: "form-control", placeholder: "Apellidos"
  .form-group
    =f.label :nombres, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :nombres, class: "form-control", placeholder: "Nombres"
  .form-group
    =f.label :identificacion, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :identificacion, class: "form-control", placeholder: "Identificación"

  .form-group
    .col-xs-5.center-xs
    = f.button :submit, class: "btn btn-raised btn-info btn-lg", value: "Guardar"

app/views/appearers/edit.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel
    .row.height-panel.middle-xs
      .col-xs-2
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_mercantile_path
                  %li.divider
                  %li
                    =link_to "Ver", mercantiles_path
              %li
                %a{:href => "javascript:void(0)"} Búsqueda
              %li
                =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Editar Compareciente
            .panel-body
              = render 'form'
              = link_to 'Regresar', @mercantile

app/views/appearers/index.html.haml
%h1 Listing appearers

%table
  %thead
    %tr
      %th User
      %th Mercantile
      %th Apellidos
      %th Nombres
      %th Identificacion
      %th
      %th
      %th

  %tbody
    - @appearers.each do |appearer|
      %tr
        %td= appearer.user
        %td= appearer.mercantile
        %td= appearer.apellidos
        %td= appearer.nombres
        %td= appearer.identificacion
        %td= link_to 'Show', appearer
        %td= link_to 'Edit', edit_appearer_path(appearer)
        %td= link_to 'Destroy', appearer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Appearer', new_appearer_path

app/views/appearers/new.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel
    .row.height-panel.middle-xs
      .col-xs-2
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_mercantile_path
                  %li.divider
                  %li
                    =link_to "Ver", mercantiles_path
              %li
                %a{:href => "javascript:void(0)"} Búsqueda
              %li
                =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Nuevo Compareciente
            .panel-body
              = render 'form'
              = link_to 'Regresar', mercantile_path(@mercantile)

app/views/appearers/show.html.haml
%p#notice= notice

%p
  %b User:
  = @appearer.user
%p
  %b Mercantile:
  = @appearer.mercantile
%p
  %b Apellidos:
  = @appearer.apellidos
%p
  %b Nombres:
  = @appearer.nombres
%p
  %b Identificacion:
  = @appearer.identificacion

= link_to 'Edit', edit_appearer_path(@appearer)
\|
= link_to 'Back', appearers_path

app/views/layouts/_navbar.html.haml
.navbar.navbar-inverse.navbar-margin
  .container-fluid.vertical-align
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-inverse-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "javascript:void(0)"} Sistema Solicitud de Inscripciones Mercantiles
    .navbar-collapse.collapse.navbar-inverse-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "javascript:void(0)"} Registro de la Propiedad y Mercantil del Cantón la Troncal

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registro de la Propiedad y Merncantil del cantón La Troncal</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <% flash.each do |type, message| %>
      <%= message %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/mercantiles/_form.html.haml
= simple_form_for(@mercantile, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-group
    =f.label :acto, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :acto, class: "form-control", placeholder: "Acto/Contrato"
  .form-group
    =f.label :observacion, class: "col-xs-3 control-label"
    .col-xs-7
      = f.input_field :observacion, class: "form-control", placeholder: "Observación"

  .form-group
    .col-xs-5.center-xs
    = f.button :submit, class: "btn btn-raised btn-info btn-lg", value: "Guardar"

app/views/mercantiles/edit.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel
    .row.height-panel.middle-xs
      .col-xs-2
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Inscripción
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_mercantile_path
                  %li.divider
                  %li
                    =link_to "Ver", mercantiles_path
              %li
                %a{:href => "javascript:void(0)"} Búsqueda
              %li
                =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Editar Inscripción
            .panel-body
              = render 'form'
              = link_to 'Regresar', mercantiles_path

app/views/mercantiles/index.html.haml
%h1 Listing mercantiles

%table
  %thead
    %tr
      %th User
      %th Acto
      %th Observacion
      %th Secuencia
      %th Fecha
      %th
      %th
      %th

  %tbody
    - @mercantiles.each do |mercantile|
      %tr
        %td= mercantile.user
        %td= mercantile.acto
        %td= mercantile.observacion
        %td= mercantile.secuencia
        %td= mercantile.fecha
        %td= link_to 'Show', mercantile
        %td= link_to 'Edit', edit_mercantile_path(mercantile)
        %td= link_to 'Destroy', mercantile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Mercantile', new_mercantile_path

app/views/mercantiles/new.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel
    .row.height-panel.middle-xs
      .col-xs-2
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Mercantil
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_mercantile_path
                  %li.divider
                  %li
                    =link_to "Ver", mercantiles_path
              %li
                %a{:href => "javascript:void(0)"} Búsqueda
              %li
                =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Nueva Inscripción
            .panel-body
              = render 'form'
              = link_to 'Back', mercantiles_path

app/views/mercantiles/show.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel.posicion
    .row.height-panel.middle-xs
      .col-xs-2.fijo
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Mercantil
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_mercantile_path
                  %li.divider
                  %li
                    =link_to "Ver", mercantiles_path
              %li
                %a{:href => "javascript:void(0)"} Búsqueda
              %li
                =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs.derecha
        .container.width-panel
          .panel.panel-primary
            .panel-heading            
              %h3.panel-title Solicitud: "#{@mercantile.secuencia}"
            .panel-body
              .table-responsive
                %table.table-striped.table-bordered.table-condensed.table-hover
                  %thead
                    %tr
                      %th Acto/Contrato
                      %th Observación
                      %th Sequencia
                      %th Año
                      %th
                      %th

                  %tbody
                    %tr
                      %td= @mercantile.acto
                      %td= @mercantile.observacion
                      %td= @mercantile.secuencia
                      %td= @mercantile.fecha
                      %td= link_to 'Edit', edit_mercantile_path(@mercantile)
                      %td= link_to 'Destroy', @mercantile, :method => :delete, :data => { :confirm => 'Are you sure?' }
          .row.center-xs
            %ul.nav.nav-pills
              %li
                = link_to 'Comparecientes', new_mercantile_appearer_path(@mercantile), class: "btn btn-success"
              %li
                %a{:href => "javascript:void(0)"} Solicitante
          .row
            .col-xs-12
              .panel.panel-primary
                .panel-heading            
                  %h3.panel-title Comparecientes
                .panel-body
                  .table-responsive
                    %table.table-striped.table-bordered.table-condensed.table-hover
                      %thead
                        %tr
                          %th Apellidos
                          %th Nombres
                          %th Identificacion
                          %th
                          %th

                      %tbody
                        - @mercantile.appearer.each do |appearer|
                          %tr
                            %td= appearer.apellidos
                            %td= appearer.nombres
                            %td= appearer.identificacion
                            %td= link_to 'Edit', edit_mercantile_appearer_path(@mercantile, appearer.id)
                            %td= link_to 'Destroy', mercantile_appearer_path(@mercantile, appearer.id), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/sequences/_form.html.haml
= simple_form_for(@sequence) do |f|
  = f.error_notification

  .form-inputs
    = f.input :secuencia
    = f.input :fecha

  .form-actions
    = f.button :submit

app/views/sequences/edit.html.haml
%h1 Editing sequence

= render 'form'

= link_to 'Show', @sequence
\|
= link_to 'Back', sequences_path

app/views/sequences/index.html.haml
%h1 Listing sequences

%table
  %thead
    %tr
      %th User
      %th Secuencia
      %th Fecha
      %th
      %th
      %th

  %tbody
    - @sequences.each do |sequence|
      %tr
        %td= sequence.user
        %td= sequence.secuencia
        %td= sequence.fecha
        %td= link_to 'Show', sequence
        %td= link_to 'Edit', edit_sequence_path(sequence)
        %td= link_to 'Destroy', sequence, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sequence', new_sequence_path

app/views/sequences/new.html.haml
%h1 New sequence

= render 'form'

= link_to 'Back', sequences_path

app/views/sequences/show.html.haml
%p#notice= notice

%p
  %b User:
  = @sequence.user
%p
  %b Secuencia:
  = @sequence.secuencia
%p
  %b Fecha:
  = @sequence.fecha

= link_to 'Edit', edit_sequence_path(@sequence)
\|
= link_to 'Back', sequences_path

app/views/welcome/index.html.haml
=render "layouts/navbar"
.jumbotron
  .container.width-panel
    .row.height-panel.middle-xs
      .col-xs-2
        .panel.panel-default.height-panel
          .panel-body
            %ul.nav.nav-pills.nav-stacked{:style => "max-width: 300px;"}
              %li.active
                =link_to "inicio", root_path
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
                  Mercantil
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Nuevo", new_mercantile_path
                  %li.divider
                  %li
                    =link_to "Ver", mercantiles_path
              %li
                %a{:href => "javascript:void(0)"} Búsqueda
              %li
                =link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      .col-xs-10.middle-xs.center-xs
        .panel.panel-default.height-panel
          .panel-body
            %h1 Bienvenido
            =image_tag "logo.png", class: "img-rounded"

app/views/welcome/unregistered.html.haml
.jumbotron
	.container.width-panel
		.row.height-panel.middle-xs.center-xs
			.col-xs-6
				.box
					.panel.panel-default
						.panel-body
							=image_tag "logo.png", class: "img-rounded", width: "200"
							%h2 Registro de la Propiedad y Mercantil del cantón La Troncal
							%p Sistema Solicitud de Inscripciones Mercantiles.
							=link_to "Iniciar sesión", new_user_session_path, class: "btn btn-primary btn-lg btn-block"